### ISSUE TITLE
Typo in ample-theme.el:616

### ISSUE THREAD

**Issue by JeanMax** [jordonbiondo/ample-theme#20]
Hey!

There is a problem with variable "ample/blue," in ample-theme.el at line [616](https://github.com/jordonbiondo/ample-theme/blob/master/ample-theme.el#L616). It should be "ample/blue" without the extra comma.
For some reasons the bug is silently ignored with emacs version 24/25, but it won't load with emacs 22!

Sweet theme anyway :)

**Comment by jordonbiondo** [comment]
That comma, though unnecessary, is syntactically valid. 
see: 

    (equal `(:foo ,:bar) '(:foo :bar)) ; => t
     (equal `(,:foo ,:bar) `(:foo :bar)) ; => t

Emacs 22 does not support color themes outside of the old color-theme library. I

**Comment by JeanMax** [comment]
Ok, you're the boss!

But without the comma, it works on emacs 22 ;)

**Comment by jordonbiondo** [comment]
My apologies, you are totally right. I am still very confused by the theme working on emacs 22 though, I could have sworn themes weren't introduced until more recently very odd.

There must have been a change in the reader or backtick evaluator because on emacs 22 this errors: 

    (let ((foo 3)) `(,foo, 3))

but on recent versions it does not. Very peculiar.

Anyway I made the change here: 75bd5c7f2fd45d6f3f68ea6f06e95175a7b4e4ce

Let me know if you have any other issues.
